### ISSUE TITLE
Issue with running the codebase

### ISSUE THREAD

**Issue by SriramSrinivas** [iHeartGraph/iSpan#1]
I was trying to run your available code via GitHub.  I do see following issues when trying to run your code after compiling. Can you please check and let me know if my input parameters are incorrect.
./ispan ../graph_converter/fw_begin.bin ../graph_converter/fw_adjacent.bin ../graph_converter/bw_begin.bin ../graph_converter/bw_begin.bin 1 0.1 0.2 0.3 0.4 2
args = 11
Thread = 1, alpha = 0, beta = 0, gamma = 0, theta = 0.4, run_times = 2
ispan: graph.cpp:74: graph::graph(const char*, const char*, const char*, const char*): Assertion `ret==edge_count' failed.
Aborted (core dumped)

**Comment by yuedeji** [comment]
Hi Sriram,

Could you provide the raw graph (text edge list) you tested?

Thanks!

**Comment by SriramSrinivas** [comment]
Hi- 
Here you go. I used the example given in your graph converter  toy list file.

1231234
%fffffff
0	1
0	2
1	0
1	2
1	3
1	4
2	0
2	1
2	3
3	1
3	2
3	4
4	1
4	3
5	6
6	5

**Comment by SriramSrinivas** [comment]
File Name for the above issue :- toy_edge_list.txt

**Comment by yuedeji** [comment]
Hi Sriram,

In your graph, is there a "%" before the first number "1231234"? Our graph converter only skips the lines starting with "%". If there isn't, you can add a "%" in front and test again.

Let me know if the error still occurs.

Thanks,
Yuede

**Comment by SriramSrinivas** [comment]
I revised and gave following input as a graph 

0       1
0       2
1       0
1       2
1       3
1       4
2       0
2       1
2       3
3       1
3       2
3       4
4       1
4       3
5       6
6       5

Still get same issue. I ran the following command :- ./ispan ../graph_converter/fw_begin.bin ../graph_converter/fw_adjacent.bin ../graph_converter/bw_begin.bin ../graph_converter/bw_begin.bin 1 0.1 0.2 0.3 0.4 1

Thread = 1, alpha = 0, beta = 0, gamma = 0, theta = 0.4, run_times = 1
ispan: graph.cpp:74: graph::graph(const char*, const char*, const char*, const char*): Assertion `ret==edge_count' failed.
Aborted (core dumped)

**Comment by yuedeji** [comment]
There is an error in your command "./ispan ../graph_converter/fw_begin.bin ../graph_converter/fw_adjacent.bin ../graph_converter/bw_begin.bin ../graph_converter/**bw_begin.bin** 1 0.1 0.2 0.3 0.4 1". The highlighted "bw_begin.bin" should be "bw_adjacent.bin". The corrected command line works under my testing. 

Another thing is, the values of alpha, beta, gamma, theta you set do not align with our setting. You can get a hint from the commands in [bash_one.sh](https://github.com/iHeartGraph/iSpan/blob/master/src/bash_one.sh)

Let me know if it works or not.

Thanks!
